### PR TITLE
Fix for bridged network and different storage location

### PR DESCRIPTION
**Pull request by kersing**
Updates to allow storage at different location (using --storage-path
option to docker-machine) and use vmrun to get IP information allowing
the use of bridged networking for the VM.
(Create will still use NAT but it can be switched to bridged after
creation completed)

### CODE REVIEW

**Comment by pecigonzalo** [comment]
Look really cool! thanks for the contribution, ill test it tomorrow and merge!

**Comment by pecigonzalo** [comment]
@kersing I was re reviewing this PR, it seems like the storage location feature was never added as part of the PR, i only see the DHCP fixes.

**Comment by kersing** [comment]
It is some time ago I worked on this, however looking at the diff I think the modifications on line 201-205 are there to solve the storage location issues I encountered.

**Comment by pecigonzalo** [comment]
But no --storage-path option

**Pull request merged**
